public class VistaAdministrador extends ObservadorEliminar {
	public Interfaz_GestionLibros_Inicio _unnamed_Interfaz_GestionLibros_Inicio_;
	public ControladorAdministrador _unnamed_ControladorAdministrador_;
	public Interfaz_GestionLibros_Agregar _unnamed_Interfaz_GestionLibros_Agregar_;
	public Interfaz_GestionLibros_Actualizar_Borrar _unnamed_Interfaz_GestionLibros_Actualizar_Borrar_;
}